/*
Ejercicio guiado: Juego de Nim. 
 */
package rcm12;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class RCMt12e12 extends javax.swing.JFrame {

    private static Nim juego;
    private JButton tablero[][];
    private int[] maxFila = {3, 5, 7};

    public RCMt12e12() {
        initComponents();
       // setLocationRelativeTo(null);
        this.juego = new Nim();
        tablero = new JButton[3][7];
        for (int f = 0; f < 3; f++) {
            for (int c = 0; c < maxFila[f]; c++) {
                tablero[f][c] = new JButton();
                tablero[f][c].addMouseListener(new java.awt.event.MouseAdapter() {
                    @Override
                    public void mouseEntered(java.awt.event.MouseEvent evt) {
                        FMouseEntered(evt);
                    }

                    @Override
                    public void mouseExited(java.awt.event.MouseEvent evt) {
                        FMouseExited(evt);
                    }
                });
                tablero[f][c].addActionListener(new java.awt.event.ActionListener() {
                    public void actionPerformed(java.awt.event.ActionEvent evt) {
                        FActionPerformed(evt);
                    }
                });
                tablero[f][c].setName(Integer.toString(f) + Integer.toString(c));
                tablero[f][c].setBackground(Color.white);
                add(tablero[f][c]);
                tablero[f][c].setBounds(c * 40, f * 40, 30, 30);
            }
        }

    }

    private void FMouseEntered(java.awt.event.MouseEvent evt) {
        String nn = evt.getComponent().getName();
        int fila = Integer.parseInt(nn.substring(0, 1));
        int col = Integer.parseInt(nn.substring(1, 2));
        for (int i = col; i < maxFila[fila]; i++) {
            tablero[fila][i].setBackground(Color.gray);
        }
    }

    private void FMouseExited(java.awt.event.MouseEvent evt) {
        evt.getComponent().setBackground(Color.red);
        String nn = evt.getComponent().getName();
        int fila = Integer.parseInt(nn.substring(0, 1));
        int col = Integer.parseInt(nn.substring(1, 2));
        for (int i = col; i < maxFila[fila]; i++) {
            tablero[fila][i].setBackground(Color.white);
        }
    }

    private void FActionPerformed(java.awt.event.ActionEvent evt) {
        evt.getSource();
        String nn = ((JButton) evt.getSource()).getName();
        int fila = Integer.parseInt(nn.substring(0, 1));
        int col = Integer.parseInt(nn.substring(1, 2));
        for (int i = col; i < maxFila[fila]; i++) {
            tablero[fila][i].setVisible(false);
        }
        jugadaUsuario(fila, col);
        jugadaMaquina();
    }

    public void jugadaUsuario(int f, int c) {
        int cant = maxFila[f] - c;
        boolean ok = juego.Juega(f, cant);
        if (juego.Fin()) {
            FinPartida("Has ganado");
        } else {
            maxFila[f] = c;
        }
    }

    public void jugadaMaquina() {
        int jugada = juego.Piensa();
        int f = (int) (jugada / 10);
        int cant = jugada % 10;
        JOptionPane.showMessageDialog(this, "Quito " + cant + " de la fila " + (f + 1));
        for (int i = maxFila[f] - cant; i < maxFila[f]; i++) {
            tablero[f][i].setVisible(false);
        }
        boolean ok = juego.Juega(f, cant);
        if (juego.Fin()) {
            FinPartida("He ganado");
        } else {
            maxFila[f] -= cant;
        }
    }

    // public void FinPartida(String mensaje) {
    //    JOptionPane.showMessageDialog(this, mensaje);
    //     System.exit(0);
    //  }
    public void FinPartida(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje);
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Otra partida?");
        if (respuesta == JOptionPane.OK_OPTION) {
            NuevaPartida();
        } else {
            System.exit(0);
        }
    }

    public void NuevaPartida() {
        
        maxFila[0] = 3;
        maxFila[1] = 5;
        maxFila[2] = 7;
        juego = new Nim();
        for (int f = 0; f < 3; f++) {
            for (int c = 0; c < maxFila[f]; c++) {
                tablero[f][c].setBackground(Color.white);
                tablero[f][c].setVisible(true);
            }
        }
        this.setVisible(true);
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Empiezo yo?");
        if (respuesta == JOptionPane.OK_OPTION ) jugadaMaquina();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RCMt12e12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RCMt12e12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RCMt12e12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RCMt12e12.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RCMt12e12().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
