/*
Realizar un programa que dibuje un tablero de ajedrez con un array de 8 x 8 botones, en
colores alternos. Al pulsar un botón, mostrará una ventana de diálogo con la fila y columna del botón
pulsado. Pista: la fila y columna pueden ser reflejadas en el nombre del botón manipulable con
setName() y getName().

Fecha: 20/03/2021
Alumno: Rafael Chamorro Maceiras
 */
package rcm12;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JOptionPane;

public class RCMt12e10 extends javax.swing.JFrame {
    static String txt;
   private JButton tablero [][];
    public RCMt12e10() {
        initComponents();
        setSize(400,400);
        setTitle ("Tablero ajedrez");
        setVisible(true);
        
        int cont=0;
        tablero = new JButton [8][8];
        for (int f = 0; f < 8 ; f++){
            for (int c = 0; c < 8 ; c++){
                cont++;
                tablero [f][c] = new JButton();
                tablero[f][c].setName(Integer.toString(f) + Integer.toString(c));
                if ((f + cont) % 2 == 0) tablero[f][c].setBackground(Color.white);
                else tablero[f][c].setBackground(Color.BLACK);
                add(tablero[f][c]);
                tablero[f][c].setBounds(c * 40, f * 40, 30, 30);
                tablero[f][c].addActionListener(new java.awt.event.ActionListener() {
                          public void actionPerformed(java.awt.event.ActionEvent evt) {
                             FActionPerformed(evt);
                             }
                });
        }
     }
    }
    private void FActionPerformed(java.awt.event.ActionEvent evt) {
        txt = ((JButton) evt.getSource()).getName();
        int fila = Integer.parseInt(txt.substring(0,1));
        int columna = Integer.parseInt(txt.substring(1,2));
        String res = String.format("Seleccionada%n fila; %d%n columna:%d",(fila+1),(columna+1));
        JOptionPane.showMessageDialog(this, res);
     }
        
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(new java.awt.GridLayout(8, 8));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RCMt12e10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RCMt12e10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RCMt12e10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RCMt12e10.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RCMt12e10().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
